[project]
name = "vector-db-at-home"
version = "2.1.0"
description = "vector db at home"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "rapidfuzz>=3.14.3",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
